### ISSUE TITLE
[PopOS 21.10] No longer able to boot PopOS's stock kernel

### ISSUE THREAD

**Issue by Aisyk** [Frogging-Family/linux-tkg#436]
Hi,

I have the same problem than this bug related to [Fedora 35](https://github.com/Frogging-Family/linux-tkg/issues/383).

When i uninstall linux-tkg with synaptic. The next reboot is in emergency mode :
`You are in rescue mode. After logging in, type journalctl -xb to view
system logs, "systemctl reboot" to reboot, "systemctl default" or “exit
to boot into default mode (or press Control-D to continue): _`

This is my journalctl related to my last boot error (command `journalctl -p err`).
https://pastebin.com/wLq4Bu0U

I try to go to `/etc/selinux/` to see if the `/etc/selinux/config` could help me, but it doesn't exist on my distribution.

**Comment by AdelKS** [comment]
It looks like stock kernel doesn't provide some additional modules: what's happening here is that `systemd` load additional modules on boot and doesn't find some.

What's the output of `tail /etc/modules-load.d/*` ?

**Comment by Aisyk** [comment]
Hi,

Thanks for your response, here is the result of the command :

```
==> /etc/modules-load.d/cups-filters.conf <==
# Parallel printer driver modules loading for cups
# LOAD_LP_MODULE was 'yes' in /etc/default/cups
lp
ppdev
parport_pc

==> /etc/modules-load.d/modules.conf <==
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.

```

**Comment by AdelKS** [comment]
Alright, given your logs (I will attach them here for posterity):

```shell
-- Boot 79cf37deec574c3386f1df808564609c --
févr. 13 10:58:16 pop-os systemd[1]: Failed to start Load Kernel Modules.
févr. 13 10:58:16 pop-os systemd-modules-load[534]: Failed to look up module alias 'lp': Function not implemented
févr. 13 10:58:16 pop-os systemd-modules-load[534]: Failed to look up module alias 'ppdev': Function not implemented
févr. 13 10:58:16 pop-os systemd-modules-load[534]: Failed to look up module alias 'parport_pc': Function not implemented
févr. 13 10:58:16 pop-os systemd-modules-load[534]: Failed to look up module alias 'ecryptfs': Function not implemented
févr. 13 10:58:16 pop-os systemd-modules-load[534]: Failed to look up module alias 'msr': Function not implemented
févr. 13 10:58:16 pop-os systemd[1]: Failed to mount Mount unit for core, revision 11993.
févr. 13 10:58:16 pop-os systemd[1]: Failed to mount Mount unit for core, revision 12603.
févr. 13 10:58:16 pop-os systemd-modules-load[614]: Failed to look up module alias 'lp': Function not implemented
févr. 13 10:58:16 pop-os systemd-modules-load[614]: Failed to look up module alias 'ppdev': Function not implemented
févr. 13 10:58:16 pop-os systemd-modules-load[614]: Failed to look up module alias 'parport_pc': Function not implemented
févr. 13 10:58:16 pop-os systemd-modules-load[614]: Failed to look up module alias 'ecryptfs': Function not implemented
févr. 13 10:58:16 pop-os systemd-modules-load[614]: Failed to look up module alias 'msr': Function not implemented
févr. 13 10:58:16 pop-os systemd[1]: Failed to start Load Kernel Modules.
févr. 13 10:58:16 pop-os systemd[1]: Failed to mount /boot/efi.
févr. 13 10:58:16 pop-os systemd[1]: Failed to mount /recovery.
févr. 13 11:03:01 pop-os /usr/bin/kernelstub[14772]: kernelstub.Drive     : ERROR    Could not find a block device for the a partition. This is a critical error and we cannot continue.
                                                      Traceback (most recent call last):
                                                        File "/usr/lib/python3/dist-packages/kernelstub/drive.py", line 56, in __init__
                                                          self.esp_fs = self.get_part_dev(self.esp_path)
                                                        File "/usr/lib/python3/dist-packages/kernelstub/drive.py", line 94, in get_part_dev
                                                          raise NoBlockDevError('Couldn\'t find the block device for %s' % path)
                                                      kernelstub.drive.NoBlockDevError: Couldn't find the block device for /boot/efi
févr. 13 11:03:01 pop-os /usr/bin/kernelstub[14775]: kernelstub.Drive     : ERROR    Could not find a block device for the a partition. This is a critical error and we cannot continue.
                                                      Traceback (most recent call last):
                                                        File "/usr/lib/python3/dist-packages/kernelstub/drive.py", line 56, in __init__
                                                          self.esp_fs = self.get_part_dev(self.esp_path)
                                                        File "/usr/lib/python3/dist-packages/kernelstub/drive.py", line 94, in get_part_dev
                                                          raise NoBlockDevError('Couldn\'t find the block device for %s' % path)
                                                      kernelstub.drive.NoBlockDevError: Couldn't find the block device for /boot/efi
févr. 13 11:04:10 pop-os /usr/bin/kernelstub[29143]: kernelstub.Drive     : ERROR    Could not find a block device for the a partition. This is a critical error and we cannot continue.
                                                      Traceback (most recent call last):
                                                        File "/usr/lib/python3/dist-packages/kernelstub/drive.py", line 56, in __init__
                                                          self.esp_fs = self.get_part_dev(self.esp_path)
                                                        File "/usr/lib/python3/dist-packages/kernelstub/drive.py", line 94, in get_part_dev
                                                          raise NoBlockDevError('Couldn\'t find the block device for %s' % path)
                                                      kernelstub.drive.NoBlockDevError: Couldn't find the block device for /boot/efi
févr. 13 11:04:10 pop-os /usr/bin/kernelstub[29146]: kernelstub.Drive     : ERROR    Could not find a block device for the a partition. This is a critical error and we cannot continue.
                                                      Traceback (most recent call last):
                                                        File "/usr/lib/python3/dist-packages/kernelstub/drive.py", line 56, in __init__
                                                          self.esp_fs = self.get_part_dev(self.esp_path)
                                                        File "/usr/lib/python3/dist-packages/kernelstub/drive.py", line 94, in get_part_dev
                                                          raise NoBlockDevError('Couldn\'t find the block device for %s' % path)
                                                      kernelstub.drive.NoBlockDevError: Couldn't find the block device for /boot/efi
févr. 13 11:04:24 pop-os systemd-cryptsetup[29239]: device-mapper: remove ioctl on cryptswap  failed: Device or resource busy
```

and this [stackoverflow issue](https://askubuntu.com/questions/814642/failed-to-lookup-alias-lp-function-not-implemented) I found, you can try to comment out the lines in `/etc/modules-load.d/cups-filters.conf` to prevent `systemd` from loading `lp`, `ppdev` and `parport_pc`. I don't even know if you need them for printing (you can test your printer if the kernel loads after that change)

**Comment by Aisyk** [comment]
Ok, so no problem for printing with the changes in `/etc/modules-load.d/cups-filters.conf` with 5.16.9-tkg-pds loaded.

In the error message (mine and below), there are 2 other modules :
```
févr. 13 10:58:16 pop-os systemd-modules-load[614]: Failed to look up module alias '**ecryptfs**': Function not implemented
févr. 13 10:58:16 pop-os systemd-modules-load[614]: Failed to look up module alias '**msr**': Function not implemented
```
Is it matter ?

**Comment by AdelKS** [comment]
According to the manual, `systemd-modules-load` looks up for modules to load in the following paths:
```
/etc/modules-load.d/*.conf
/run/modules-load.d/*.conf
/usr/lib/modules-load.d/*.conf
```
See if `ecryptfs` and `msr` is in one of these folders in a `.conf` file, you can see which package owns that file.

Basically, `linux-tkg` seems to be providing extra kernel modules that are not in the original official Ubuntu image: this is normal as it is newer. But I do not understand how config files got automatically edited to load new kernel modules.

**Comment by AdelKS** [comment]
Hello, I went through this issue again: have you tried `sudo update-initramfs -k all` ? Actually now that I think of it, maybe that's the problem :thinking:

**Comment by rpatterson** [comment]
> [According to the manual](https://www.man7.org/linux/man-pages/man5/modules-load.d.5.html), `systemd-modules-load` looks up for modules to load in the following paths:

In case this helps someone else find this, the above also helped me "dual booting" my Pop!_OS install under Microsoft's WSL.

**Comment by AdelKS** [comment]
Hello, now that I think of it, did you have SELinux enabled on Ubuntu ?

**Comment by Aisyk** [comment]
Too old, and this problem seems to be resolved (tkg -> xanmod kernels).
